# Site settings
title: "Modern Apprenticeship"
email: "paul@8thlight.com"
description: "Modern Apprenticeship blog by Paul Pagel"
baseurl: ""
url: "http://modern-apprenticeship.8thlight.com"

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: /css/_sass
